### ISSUE TITLE
Issue: Permission denied

### ISSUE THREAD

**Issue by MingBit** [jyyulab/SJARACNe#11] opened 2019-06-13 14:44 UTC
Hallo,

Thanks for the great development.
I'm testing this package with example code shown in the main page. Here comes an issue of Permission denied. `Sudo` couldn't fix the issue. 

Any ideas? many thanks.

**Comment by adamdingliang** [comment] 2019-06-13 18:17
Hi,

As I cannot reproduce your problem in my computing environment, can you be more specific about the issue? Like which platform were you trying to install? Where did you install?

Thanks!

**Comment by MingBit** [comment] 2019-06-14 08:52
thanks for the fast response!
I was testing on Linux and docker container. Package was downloaded via git clone 
`git clone https://github.com/jyyulab/SJARACNe` ;

 installed by `pip install **-r** requirements.txt` (**python-igraph==0.7.1.post6**)

set up by `python setup.py install`

tested by `sjaracne TF test_data/inputs/BRCA100.exp .test_data/inputs/tf.txt test_data/outputs/`

Issue: `test_data/outputs/SJARACNE_TF/SJARACNE_scripts/02_bootstrap_TF.sh: 70: test_data/outputs/SJARACNE_TF/SJARACNE_scripts/02_bootstrap_TF.sh: sjaracne.linux: Permission denied`

**Comment by adamdingliang** [comment] 2019-06-15 21:46
By default, sjaracne.linux will be installed to the site-packages directory in your python. You may check the permission of the binary there. Or you may try to rebuild sjaracne.linux using the Makefile before the installing.

**Comment by MingBit** [comment] 2019-06-17 08:17
okay. .
I also gave the full permission to folders `test_data` and `SJARACNE/SJARACNE/bin`
 it didn't work either :(

**Closed** 2019-07-19 13:40 UTC
